name: Lewis Buckley Development
author: Lewis Buckley
markdown: redcarpet
pygments: true
description: Ruby on Rails specialists in Bristol
github: http://www.github.com/lewispb
twitter: http://www.twitter.com/lewispb
facebook: http://www.facebook.com
linkedin: https://www.linkedin.com/pub/lewis-buckley/20/36b/aa7
email: info@lewisbuckley.co.uk
location: 51°27'N   2°35'W
title: Lewis Buckley Development

##Make sure to edit the above fields, especially for disqus.

